wget http://raw.githubusercontent.com/7vik/mats_research_sprint/master/exploratory_notebooks/logit_lens_decomposed_datapoint_12.html
wget https://raw.githubusercontent.com/7vik/mats_research_sprint/master/exploratory_notebooks/day_9_dishonesty_block_every_patching_log_prob_diff_metric.html
wget https://raw.githubusercontent.com/7vik/mats_research_sprint/master/exploratory_notebooks/logit_lens_accumulated.html
wget https://raw.githubusercontent.com/7vik/mats_research_sprint/master/exploratory_notebooks/logit_lens_decomposed.html
wget https://raw.githubusercontent.com/7vik/mats_research_sprint/master/exploratory_notebooks/day_9_dishonesty_block_every_patching_kld_metric.html
wget https://github.com/7vik/mats_research_sprint/raw/master/exploratory_notebooks/day_12_attn_patching_long_term_logprob_diff.html
wget https://raw.githubusercontent.com/7vik/mats_research_sprint/master/exploratory_notebooks/day_8_activation_patching_attn_heads_all_pos_batched.html

wget https://github.com/jmsdao/mats5/raw/main/directions/honesty_mistral.pt
wget https://github.com/jmsdao/mats5/raw/main/figs/logprob-diffs-heatmap.html
wget https://github.com/jmsdao/mats5/raw/main/figs/attn-patterns-input-12.html
wget https://github.com/jmsdao/mats5/raw/main/figs/logit_lens_decomp.html
wget https://github.com/jmsdao/mats5/raw/main/figs/logit_lens_accum.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-30-33-34-plus1-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-30-33-34-plus1-lpd.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-30-34-plus1-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-30-34-plus1-lpd.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-all-but-one-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-all-but-one-lpd.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-keep-one-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/pos-injection-keep-one-lpd.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp1-block-every-kld-batchmean.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp1-block-every-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp1-block-every-logprob-diff-batchmean.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp1-block-every-logprob-diff.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp2-attn-all-pos-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp2-attn-all-pos-logprob-diff.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp2-mlp-all-pos-kld.html
wget https://github.com/jmsdao/mats5/raw/main/figs/patch-exp2-mlp-all-pos-logprob-diff.html